### ISSUE TITLE
Introduce CI

### ISSUE THREAD

**Issue by szepeviktor** [WPBP/WordPress-Plugin-Boilerplate-Powered#160]
- [x] Fix Composer config #161 
- [x] Set up PHPStan #163 
- [x] Choose a Coding Standard #166
- [x] Enable CI #168 

I mean CI for this repo, not CI for plugins made from this repo.

@Mte90 What CS would you follow in PHP code?
PSR-12, WPCS, Neutron, other?

**Comment by szepeviktor** [comment]
Could you point me to a full-fledged plugin made from this boilerplate.
I'd set up PHPStan for all possible problems.

**Comment by Mte90** [comment]
I am looking to the various pr, thanks!
Right now I am using this phpcs https://github.com/codeatcode/codeatcs that is downloaded by https://github.com/WPBP/generator but is replaceable during the boilerplate generation.

**Comment by szepeviktor** [comment]
> I am using this phpcs [codeatcode/codeatcs](https://github.com/codeatcode/codeatcs)

Thank you.
Could you make it a Composer package?

e.g. https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/blob/master/composer.json

**Comment by Mte90** [comment]
Do you think that is useful? right now that xml is downloaded by the generator and placed in the root of the plugin so anyone can customize it based on their needs.  
If will do a package this require to create a new one etc...

**Comment by szepeviktor** [comment]
Every PHP ruleset is distributed as a Composer package.

Composer even has a special package type for that: `"type": "phpcodesniffer-standard",`

**Comment by Mte90** [comment]
I will do a package asap.

**Comment by Mte90** [comment]
Package generated https://packagist.org/packages/codeatcode/codeatcs

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
Are you compatible with the highly popular https://github.com/Dealerdirect/phpcodesniffer-composer-installer#how-it-works ?

**Comment by Mte90** [comment]
Seems yes because I got that `PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility,../../phpcompatibility/phpcompatibility-paragonie,../../phpcompatibility/phpcompatibility-wp,../../phpcsstandards/phpcsdevcs,../../slevomat/coding-standard,../../wp-coding-standards/wpcs`

**Comment by szepeviktor** [comment]
Where is `codeatcs`??

**Comment by Mte90** [comment]
You are right, checking the tool code require that the file is called `ruleset` so I will do a new release.
